version: '3.8'

services:
  workshop:
    image: anthonychristidis/spatial-workshop:v1.4
    ports:
      - "8888:8888"
    command: >
      micromamba run -p /opt/conda/env jupyter lab 
      --ip=0.0.0.0 
      --port=8888 
      --no-browser 
      --allow-root 
      --ServerApp.token='' 
      --ServerApp.password='' 
      --ServerApp.disable_check_xsrf=True
      --ServerApp.open_browser=False