name: spatial-workshop
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - ipywidgets
  - black
  - jupyter-black
  - spatialdata
  - spatialdata-io
  - spatialdata-plot
  - napari-spatialdata
  - scanpy
  - squidpy
  - napari
  - pyqt=5
  - geopandas
  - python-igraph
  - leidenalg
  - matplotlib